services:

  redis:
    image: redis:latest
    ports: [ "6379:6379" ]

  ratelimiter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ratelimiter
    depends_on: [ redis ]

  service1:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "yarn", "start-service1" ]
    depends_on: [ redis ]
    ports: [ "3000:3000" ]

  service2:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "yarn", "start-service2" ]
    depends_on: [ redis ]
    ports: [ "3001:3001" ]

  service3:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "yarn", "start-service3" ]
    depends_on: [ redis ]
    ports: [ "3002:3002" ]
