services:

  redis:
    image: redis:latest
    ports: [ "6379:6379" ]

  service1:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "yarn", "start-service1" ]
    depends_on: [ redis ]
    environment:
      - REDIS_URL=redis
      - REDIS_PORT=6379
    ports: [ "3000:3000" ]

  service2:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "yarn", "start-service2" ]
    depends_on: [ redis ]
    environment:
      - REDIS_URL=redis
      - REDIS_PORT=6379
    ports: [ "3001:3001" ]

  service3:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "yarn", "start-service3" ]
    depends_on: [ redis ]
    environment:
      - REDIS_URL=redis
      - REDIS_PORT=6379
    ports: [ "3002:3002" ]

  clientapp:
    build:
      context: ./src/clientapp/
      dockerfile: Dockerfile
    ports: [ "5173:5173" ]
